CREATE TABLE quiz_me_flashcards (
    flashcard_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT REFERENCES quiz_me_users(username) ON DELETE CASCADE NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL
);